apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod # değişti
  labels:
    name: result-app-pod # değişti
    app: demo-voting-app # değişti
spec:
  containers:
  - name: result-app # değişti
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80